# coding: utf-8

from decouple import config
import os

BASE_DIR = os.path.dirname(__file__)

MONGO_DATABASE_URL = config('MONGO_DATABASE_URL')
MONGO_USER = config('MONGO_USER')
MONGO_PASSWORD = config('MONGO_PASSWORD')

AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')

MINIO_HOST = config('MINIO_HOST')
MINIO_ENDPOINT = config('MINIO_ENDPOINT')

KUBESPAWNER_SERVICES_ENDPOINT = config('KUBESPAWNER_SERVICES_ENDPOINT')
DATASETS_SERVICES_ENDPOINT = config('DATASETS_SERVICES_ENDPOINT')
PROJECTS_SERVICES_ENDPOINT = config('PROJECTS_SERVICES_ENDPOINT')

ETCD_PORT = 2379
ETCD_HOST = config('ETCD_HOST')

KUBE_NAMESPACE = config('KUBE_NAMESPACE')
DEPLOYMENT_MIDDLEWARES = ["ilyde-deployment-replacepathregex"]

MLFLOW_TRACKING_URI = config("MLFLOW_TRACKING_URI")



