##
## Copyright (c) 2020-2021 Hopenly srl.
##
## This file is part of Ilyde.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ name }}
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: ilyde
      securityContext:
        runAsUser: 12574
        runAsGroup: 12574
        fsGroup: 12574
        privileged: true
      volumes:
        - name: jobdir
          emptyDir: {}
      initContainers:
        - name: initializer
          image: ilyde/job-initializer:1.0.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "cp -R /opt/ilyde/* /jobdir"]
          volumeMounts:
            - name: jobdir
              mountPath: "/jobdir"
      containers:
        - name: runner
          image: {{ environment }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["/bin/bash", "/opt/ilyde/entrypoint.sh"]
          args:
            {% for arg in args %}
            - "{{ arg }}"
            {% endfor %}
          env:
            - name: ILYDE_WORKING_DIR
              value: "/ilyde"
            - name: IP_ADDR
              value: "0.0.0.0"
            - name: ILYDE_JOB_ID
              value: "{{ JOB_ID }}"
            - name: AWS_ACCESS_KEY_ID
              value: "{{ AWS_ACCESS_KEY_ID }}"
            - name: AWS_SECRET_ACCESS_KEY
              value: "{{ AWS_SECRET_ACCESS_KEY }}"
            - name: MINIO_HOST
              value: "{{ MINIO_HOST }}"
            - name: MINIO_ENDPOINT
              value: "{{ MINIO_ENDPOINT }}"
            - name: ETCD_HOST
              value: "{{ ETCD_HOST }}"
            - name: DATASETS_SERVICES_ENDPOINT
              value: "{{ DATASETS_SERVICES_ENDPOINT }}"
            - name: PROJECTS_SERVICES_ENDPOINT
              value: "{{ PROJECTS_SERVICES_ENDPOINT }}"
            - name: MLFLOW_TRACKING_URI
              value: "{{ MLFLOW_TRACKING_URI }}"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "{{ MLFLOW_S3_ENDPOINT_URL }}"

          volumeMounts:
            - name: jobdir
              mountPath: /opt/ilyde
          resources:
            limits:
              cpu: {{ cpus_limit }}
              memory: {{ ram_limit }}
            requests:
              cpu: {{ cpus_request }}
              memory: {{ ram_request }}

      restartPolicy: Never
      nodeSelector:
        platform.ilyde.it/instancegroup: {{ instancegroup }}
