apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ name }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: ilyde-disk
